Repository nearform/k8s-kurated-addons, pull requests merged in 2023-01, with the labels that each got.

#2 docs: added basic diagrams for quick start and CI
  CONTRIBUTING.MD
  README.md
  docs/img/inner-workings/k8s-addons-internals.excalidraw
  docs/img/inner-workings/k8s-addons-internals.png
  docs/img/quick-start/k8s-addons-quick-start.excalidraw
  docs/img/quick-start/k8s-addons-quick-start.png
Labels: documentation, prio/P2

#4 docs: Fix typo
  README.md
Labels: enhancement, prio/P2

#3 chore: Prometheus podMonitor selector removed
  Makefile
  addons/kube-prometheus-stack/values.yaml
Labels: enhancement, prio/P3

#5 docs: renovate bot and release please adrs
  architectural-design-records/dependency-management-automation.md
  architectural-design-records/release-management-automation.md
  docs/img/inner-workings/k8s-addons-internals.excalidraw
  docs/img/quick-start/k8s-addons-quick-start.excalidraw
Labels: documentation, prio/P2

#1 chore: Improve the contributor onboarding experience
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  README.md
Labels: enhancement

#6 docs: argocd configuration readme
  README.md
Labels: documentation

#8 feat: Sample Grafana dashboard
  docs/SAMPLE_PROMETHEUS_APP.md
  examples/sample-prometheus-app/sample-prometheus-app.yaml
Labels: enhancement

#7 chore: Refine CI workflows
  .github/renovate-config.js
  .github/workflows/integration.yaml
  .github/workflows/preview.yaml
  .github/workflows/renovate.yaml
Labels: enhancement

#19 chore: Align version for addons and app-of-apps to currently released
  addons/argocd/Chart.yaml
  addons/cert-manager/Chart.yaml
  addons/dex/Chart.yaml
  addons/istio/base/Chart.yaml
  addons/istio/ingressgateway/Chart.yaml
  addons/istio/istiod/Chart.yaml
  addons/kube-prometheus-stack/Chart.yaml
  app-of-apps/Chart.yaml
Labels: enhancement

#28 docs: Knative deletion race condition resolution
  docs/KNOWN_ISSUES.md
Labels: documentation

#29 chore: Refine preview/integration workflows to skip docs PRs
  .github/workflows/integration.yaml
  .github/workflows/preview.yaml
Labels: enhancement

#30 fix: Downgrade ArgoCD traffic to HTTP
  Tiltfile
  addons/argocd/values.yaml
Labels: bug

#33 feat: Add OpenTelemetry addon
  .envrc
  .github/workflows/integration.yaml
  addons/opentelemetry/opentelemetry-collector/Chart.yaml
  addons/opentelemetry/opentelemetry-collector/values.yaml
  addons/opentelemetry/opentelemetry-operator/Chart.yaml
  addons/opentelemetry/opentelemetry-operator/values.yaml
  app-of-apps/values.yaml
  docs/ADDONS.md
  manifests/app-of-apps.yaml
Labels: enhancement

#40 chore: Migrate integration test to a larger Linux runner
  .github/workflows/integration.yaml
Labels: enhancement

#34 docs: Add How to create a new release section
  CONTRIBUTING.md
Labels: documentation

#42 chore: Set 15m timeout for integration/unit testing pipelines
  .github/workflows/integration.yaml
  .github/workflows/preview.yaml
Labels: enhancement

#41 chore: Migrate to the official Renovate Github App
  .github/renovate-config.js
  .github/renovate.json
  .github/workflows/renovate.yaml
  CONTRIBUTING.md
Labels: enhancement

#31 feat: Move app-of-apps manifest to helm-chart
  .github/workflows/assets.yaml
  .gitignore
  README.md
  Tiltfile
  manifests/bootstrap/.helmignore
  manifests/bootstrap/Chart.yaml
  manifests/bootstrap/overrides.local.yaml.tmpl
  manifests/bootstrap/templates/app-of-apps.yaml
  manifests/bootstrap/values.yaml
Labels: enhancement
